name: AeroWarp
version: '${version}'
main: xyz.jeelzzz.aerowarp.AeroWarp
api-version: "1.20"
authors: [ jeelzzz ]
description: A simple, lightweight warp plugin.

commands:
  warp:
    description: Teleport to a warp.
  setwarp:
    description: Create a warp.